# Generated by Django 5.0.6 on 2024-07-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('type', models.CharField(max_length=250, verbose_name='Тип')),
                ('quantity', models.CharField(max_length=250, verbose_name='Количество')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
