# Generated by Django 5.0.6 on 2024-07-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250),
        ),
    ]
