# Generated by Django 5.0.6 on 2024-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0002_jewelry_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
