# Generated by Django 5.0.6 on 2024-07-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0006_types_jewelry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.types'),
        ),
    ]
