# Generated by Django 5.0.6 on 2024-07-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0007_alter_jewelry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_for_cat'),
        ),
    ]
