# Generated by Django 5.0.6 on 2024-07-21 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0008_types_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Тип товаров'},
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='quantity',
            field=models.IntegerField(max_length=250, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='jewelry',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jewelry.types', verbose_name='Тип изделия'),
        ),
    ]
