# Generated by Django 5.0.6 on 2024-07-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0009_uploadfiles_alter_types_options_alter_jewelry_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
