# Generated by Django 5.0.6 on 2024-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0011_alter_uploadfiles_options_alter_jewelry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='test',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Проба'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='type_metall',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Тип металла'),
        ),
        migrations.AddField(
            model_name='jewelry',
            name='weight',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='types',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
