# Generated by Django 5.0.6 on 2024-07-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0013_alter_jewelry_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото2'),
        ),
    ]
