# Generated by Django 5.0.6 on 2024-07-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jewelry', '0015_alter_jewelry_image_alter_jewelry_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
    ]
